
TTF_ByteSwappedUNICODE:
    jmp [real_TTF_ByteSwappedUNICODE]

TTF_CloseFont:
    jmp [real_TTF_CloseFont]

TTF_FontAscent:
    jmp [real_TTF_FontAscent]

TTF_FontDescent:
    jmp [real_TTF_FontDescent]

TTF_FontFaceFamilyName:
    jmp [real_TTF_FontFaceFamilyName]

TTF_FontFaceIsFixedWidth:
    jmp [real_TTF_FontFaceIsFixedWidth]

TTF_FontFaceStyleName:
    jmp [real_TTF_FontFaceStyleName]

TTF_FontFaces:
    jmp [real_TTF_FontFaces]

TTF_FontHeight:
    jmp [real_TTF_FontHeight]

TTF_FontLineSkip:
    jmp [real_TTF_FontLineSkip]

TTF_GetFontHinting:
    jmp [real_TTF_GetFontHinting]

TTF_GetFontKerning:
    jmp [real_TTF_GetFontKerning]

TTF_GetFontOutline:
    jmp [real_TTF_GetFontOutline]

TTF_GetFontStyle:
    jmp [real_TTF_GetFontStyle]

TTF_GlyphIsProvided:
    jmp [real_TTF_GlyphIsProvided]

TTF_GlyphMetrics:
    jmp [real_TTF_GlyphMetrics]

TTF_Init:
    jmp [real_TTF_Init]

TTF_Linked_Version:
    jmp [real_TTF_Linked_Version]

TTF_OpenFont:
    jmp [real_TTF_OpenFont]

TTF_OpenFontIndex:
    jmp [real_TTF_OpenFontIndex]

TTF_OpenFontIndexRW:
    jmp [real_TTF_OpenFontIndexRW]

TTF_OpenFontRW:
    jmp [real_TTF_OpenFontRW]

TTF_Quit:
    jmp [real_TTF_Quit]

TTF_RenderGlyph_Blended:
    jmp [real_TTF_RenderGlyph_Blended]

TTF_RenderGlyph_Shaded:
    jmp [real_TTF_RenderGlyph_Shaded]

TTF_RenderGlyph_Solid:
    jmp [real_TTF_RenderGlyph_Solid]

TTF_RenderText_Blended:
    jmp [real_TTF_RenderText_Blended]

TTF_RenderText_Shaded:
    jmp [real_TTF_RenderText_Shaded]

TTF_RenderText_Solid:
    jmp [real_TTF_RenderText_Solid]

TTF_RenderUNICODE_Shaded:
    jmp [real_TTF_RenderUNICODE_Shaded]

TTF_RenderUNICODE_Solid:
    jmp [real_TTF_RenderUNICODE_Solid]

TTF_RenderUTF8_Blended:
    jmp [real_TTF_RenderUTF8_Blended]

TTF_RenderUTF8_Shaded:
    jmp [real_TTF_RenderUTF8_Shaded]

TTF_RenderUTF8_Solid:
    jmp [real_TTF_RenderUTF8_Solid]

TTF_SetFontHinting:
    jmp [real_TTF_SetFontHinting]

TTF_SetFontKerning:
    jmp [real_TTF_SetFontKerning]

TTF_SetFontOutline:
    jmp [real_TTF_SetFontOutline]

TTF_SetFontStyle:
    jmp [real_TTF_SetFontStyle]

TTF_SizeText:
    jmp [real_TTF_SizeText]

TTF_SizeUTF8:
    jmp [real_TTF_SizeUTF8]

TTF_WasInit:
    jmp [real_TTF_WasInit]
